# Generated by Django 4.2.15 on 2024-08-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='details',
            new_name='detail',
        ),
    ]
