# Generated by Django 4.2.15 on 2024-08-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_details_service_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='details',
            new_name='detail',
        ),
    ]
