# Generated by Django 4.2.15 on 2024-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subplan_subplanfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subplanfeature',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
