# Generated by Django 4.2.15 on 2024-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_subplan_price_alter_subplanfeature_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='highlight',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
