# Generated by Django 4.2.15 on 2024-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
