# Generated by Django 4.2.15 on 2024-08-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
