# Generated by Django 4.2.15 on 2024-08-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_notify_read_by_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifuserstatus', to='main.notify')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='main.notify')),
            ],
        ),
    ]
