# Generated by Django 4.2.15 on 2024-09-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_assignsubscriber_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifuserstatus',
            options={'verbose_name_plural': 'Notification Status'},
        ),
    ]
