# Generated by Django 4.2.15 on 2024-09-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_notifuserstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='valid_days',
            field=models.IntegerField(null=True),
        ),
    ]
