# Generated by Django 4.2.15 on 2024-09-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_subplan_valid_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subplanfeature',
            old_name='title',
            new_name='feature',
        ),
    ]
