# Generated by Django 4.2.15 on 2024-09-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_banners_options_alter_enquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='trainer',
            name='facebook',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pinterest',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='x',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='youtube',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
