# Generated by Django 4.2.15 on 2024-09-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_x_trainer_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='twitter',
            new_name='wesbite',
        ),
    ]
