# Generated by Django 4.2.15 on 2024-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_twitter_trainer_wesbite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='pinterest',
            new_name='instagram',
        ),
        migrations.AddField(
            model_name='trainer',
            name='twitter',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
