# Generated by Django 4.2.15 on 2024-09-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_pinterest_trainer_instagram_trainer_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='wesbite',
            new_name='blog',
        ),
    ]
