# Generated by Django 4.2.15 on 2024-09-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_traineracheivement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='salry',
            field=models.IntegerField(default=1),
        ),
    ]
