# Generated by Django 4.2.15 on 2024-09-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_trainer_salry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='salry',
            new_name='salary',
        ),
    ]
