# Generated by Django 4.2.15 on 2024-09-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_trainersalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainersalary',
            options={'verbose_name_plural': "Trainers' Salaries"},
        ),
    ]
