# Generated by Django 4.2.15 on 2024-09-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_enquiry_email_alter_enquiry_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
