# Generated by Django 4.2.15 on 2024-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_trainermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainermessage',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
